# Generated by Django 3.2.8 on 2022-03-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('weather', models.FloatField(max_length=10)),
                ('tempreture', models.FloatField(max_length=10)),
                ('Humidity', models.FloatField(max_length=20)),
            ],
        ),
    ]
