# Generated by Django 3.2.8 on 2022-03-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webweather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='datas',
        ),
    ]
