# Generated by Django 3.2.8 on 2022-03-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webweather', '0002_rename_data_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='weather',
            field=models.CharField(max_length=10),
        ),
    ]
